OEL-309: Add OE Whitelabel theme scaffold files.
openeuropa/oe_whitelabel pull request #1
Opened 2021-07-29 07:10 UTC by 10atm-blue

PR goals:
- Add Whitelabel theme file structure

2021-08-26 15:16 UTC, drishu reviewed
https://github.com/openeuropa/oe_whitelabel/issues/2 <-- click me

2021-08-30 08:55 UTC, claudiu-cristea approved these changes

2021-08-30 08:55 UTC, drishu approved these changes

2021-08-30 08:56 UTC, drishu requested changes
was to fast

2021-08-30 08:56 UTC, claudiu-cristea requested changes
Undo approval.

2021-09-07 10:55 UTC, drishu approved these changes, later dismissed

2021-09-07 12:32 UTC, abel-santos-corral approved these changes
Reviewed all files. File .phpunit.result.cache eliminated from git and added to .gitignore file. Also checked the assets.

2021-09-07 12:32 UTC, abel-santos-corral commented on .phpunit.result.cache
> +{"version":1,"defects":[],"times":[]}
This file must be eliminated.

2021-09-07 12:34 UTC, drishu approved these changes

2021-09-07 12:37 UTC, claudiu-cristea approved these changes

2021-09-07 12:38 UTC, merged