OEL-455 [oe_whitelabel] footer
openeuropa/oe_whitelabel pull request #10
Opened 2021-09-14 10:19 UTC by escuriola

Manage oe_whitelabel footer blocks for EU and EC.

2021-09-14 23:09 UTC, drishu requested changes

2021-09-14 23:09 UTC, drishu commented on composer.json
> +        "openeuropa/oe_corporate_blocks": "^4.2",
Let's move this to require dev as it's not needed by the theme, but by the module

2021-09-14 23:09 UTC, drishu commented on modules/oe_whitelabel_footer/oe_whitelabel_footer.info.yml
> +  - openeuropa:oe_corporate_blocks
Since Francesco asked to use a helper module, and now we have it, lets move the dependency in there, we can remove this then

2021-09-14 23:09 UTC, drishu commented on runner.yml.dist
> +    - "./vendor/bin/drush en oe_whitelabel_footer -y"
now that its a dependency on helper, we can remove this

2021-09-14 23:09 UTC, drishu commented on modules/oe_whitelabel_helper/src/TwigExtension/TwigExtension.php
> +  public function getFilters(): array {
remove this, its not used

2021-09-14 23:09 UTC, drishu commented on modules/oe_whitelabel_helper/src/TwigExtension/TwigExtension.php
> +
add a block renderer, we will use it for the corporate logo in the block

2021-09-14 23:09 UTC, drishu commented on templates/layouts/ec_footer_bottom_middle.html.twig
> +<h2> {{ contact_eu_title| t }}  </h2>
we just need the service_navigation here

2021-09-14 23:09 UTC, drishu commented on templates/layouts/ec_footer_bottom_right.html.twig
> +<h2> {{ eu_institutions_title| t }} </h2>
we can use something more generic like `title` and `links`

2021-09-14 23:09 UTC, drishu commented on templates/layouts/ec_footer_bottom_right.html.twig
> +        'icon_position': eu_link['link']['icon_position']
`icon` is missing

2021-09-14 23:09 UTC, drishu commented on templates/layouts/ec_footer_bottom_right.html.twig
> +        'path': eu_link['link']['path'],
path is a object passed that needs to be rendered
```suggestion
        'path': eu_link['link']['path']|render,
```

2021-09-14 23:09 UTC, drishu commented on templates/layouts/ec_footer_top_left.html.twig
> +<h2> {{ project_name }} </h2>
lets use everywhere h4, h2 is to big
here call the link pattern

2021-09-14 23:09 UTC, drishu commented on templates/layouts/ec_footer_top_middle.html.twig
> +<h2> {{ contact_title| t }} {{ project_name }} </h2>
move this template to eu, ec harmonized group 2 does not seem to use top

2021-09-14 23:09 UTC, drishu commented on templates/layouts/ec_footer_top_middle.html.twig
> +<h2> {{ follow_title| t }} </h2>
we can print generic sections

2021-09-14 23:09 UTC, drishu commented on templates/layouts/ec_footer_top_right.html.twig
> +{% if optional_links_links is defined and optional_links_links is not empty and optional_links_links is iterable %}
move this to eu, also, print generic sections

2021-09-14 23:09 UTC, drishu commented on templates/layouts/eu_footer_left.html.twig
> +Logo
call the twig function for block rendering mentioned earlier, with the eu corporate logo block plugin id

2021-09-14 23:09 UTC, drishu commented on templates/layouts/eu_footer_middle.html.twig
> +<h2> {{ contact_eu_title| t }}  </h2>
```suggestion
<h2> {{ contact_eu_title|t }}  </h2>
```

2021-09-14 23:09 UTC, drishu commented on templates/layouts/eu_footer_middle.html.twig
> +  <li>{{ pattern('link', {
you can call contact_link directly
```suggestion
  <li>{{ pattern('link', contact_link) }}</li>
```
same for below loops

2021-09-14 23:09 UTC, drishu commented on templates/layouts/eu_footer_right.html.twig
> +    <li>{{ pattern('link', {
```suggestion
    <li>{{ pattern('link', eu_link) }}</li>
```

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-ec-footer.html.twig
> +  {% set _top_sections = [
remove this section

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-ec-footer.html.twig
> +      'logo': 'logo',
```suggestion
'title': {
        'link': {
          'label': site_specific_footer.site_identity,
          'path': url('<front>')|render,
        }
      }
```

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-ec-footer.html.twig
> +      'contact_eu_title': 'Contact the EU',
remove all these, you only need 
```suggestion
'links': bcl_footer_links(corporate_footer.service_navigation),
```

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-ec-footer.html.twig
> +      'eu_institutions_title': 'EU Institutions',
and here you need
```suggestion
'links': bcl_footer_links(corporate_footer.legal_navigation)
```

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-ec-footer.html.twig
> +    'top_sections': _top_sections,
remove

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-eu-footer.html.twig
> +#}
compute _section_2 and _section_3 from the link provided in the ticket (its copy paste)

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-eu-footer.html.twig
> +      'logo': 'logo',
```suggestion
'title': {
      'link': {
        'label': site_specific_footer.site_identity,
        'path': url('<front>')|render
      }
    },
```

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-eu-footer.html.twig
> +      'path': url('<front>')
'description': site_owner ? 'This site is managed by the @name'|t({'@name': site_owner}),

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-eu-footer.html.twig
> +      'section_id': 'eu_footer_middle',
move all this to a new bottom_section

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-eu-footer.html.twig
> +      'eu_institutions_title':  corporate_footer.institution_links_title,
move all this to a new bottom_section

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-eu-footer.html.twig
> +
add bottom section

2021-09-14 23:09 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-eu-footer.html.twig
> +    'top_sections': _top_sections
add bottom sections

2021-09-14 23:58 UTC, drishu requested changes

2021-09-14 23:58 UTC, drishu commented on templates/patterns/footer/pattern-footer.html.twig
> +<footer>
the container from page does the job, this footer tag is redundant and so is below container

2021-09-14 23:58 UTC, drishu commented on tests/src/Kernel/FooterBlockTest.php
> +    'oe_whitelabel_footer',
we wont have this anymore

2021-09-14 23:58 UTC, drishu commented on tests/src/Kernel/FooterBlockTest.php
> +    'block',
you are missing the oe_corporate_blocks and its dependencies

2021-09-14 23:58 UTC, drishu commented on tests/src/Kernel/FooterBlockTest.php
> +class FooterBlockTest extends KernelTestBase {
this needs to be  SparqlKernelTestBase

2021-09-15 09:32 UTC, drishu submitted a review, later dismissed

2021-09-15 09:34 UTC, abel-santos-corral approved these changes
Approved

2021-09-15 14:35 UTC, drishu approved these changes

2021-09-15 14:35 UTC, merged