OEL-1317: Improve navbar search form.
openeuropa/oe_whitelabel pull request #100
Opened 2022-03-24 16:27 UTC by escuriola

2022-03-27 14:09 UTC, GilNovacomm submitted a review, later dismissed

2022-03-28 17:42 UTC, drishu requested changes

2022-03-28 17:42 UTC, drishu commented on modules/oe_whitelabel_search/src/Form/SearchForm.php
> +    $form['#attributes']['class'][] = 'd-flex mt-3 mt-lg-0';
lets add classes only in form--oe-whitelabel-search-form.html.twig

2022-03-28 17:42 UTC, drishu commented on modules/oe_whitelabel_search/templates/form--oe-whitelabel-search-form.html.twig
> +<form{{ attributes.addClass('d-flex', 'mt-3', 'mt-lg-0', 'w-100', 'submittable') }}>
keep only d-flex mt-3 mt-lg-0

2022-03-29 06:18 UTC, drishu commented on templates/overrides/search/form-element--search-api-autocomplete.html.twig
> +  'w-100',
what does this do for us?

2022-03-29 06:20 UTC, drishu commented on modules/oe_whitelabel_search/templates/block--oe-whitelabel-search-form.html.twig
> +{#
we should move all the templates from this folder to /templates/search

2022-04-14 06:20 UTC, drishu commented on modules/oe_whitelabel_search/templates/form--oe-whitelabel-search-form.html.twig
> +<form{{ attributes.addClass('d-flex', 'mt-3', 'mt-lg-0', 'w-100', 'submittable') }}>
do we need "submittable" ?

2022-04-14 06:21 UTC, drishu commented on modules/oe_whitelabel_search/templates/block--oe-whitelabel-search-form.html.twig
> +{#
don't forget about this one

2022-04-14 07:02 UTC, drishu commented on modules/oe_whitelabel_search/templates/block--oe-whitelabel-search-form.html.twig
> + * Available variables:
as we did in the oebt PR lets remove these as they are there in block.html.twig already

2022-04-14 07:08 UTC, drishu requested changes
2 issues I saw now
<img width="610" alt="Screenshot 2022-04-14 at 10 04 03" src="https://user-images.githubusercontent.com/11507647/163332179-559e5f1c-471b-4c11-8657-65e7c22c405c.png">
we need a template for the navbar_right region and wrap {{ content}} in a div.nav
<img width="610" alt="Screenshot 2022-04-14 at 10 04 15" src="https://user-images.githubusercontent.com/11507647/163332281-2f3903db-213a-4e61-9bd9-20f2929cfbe2.png">
we need to add class ps-0 to the site name because  we have to much passing on the left, or get rid of the "bcl-header__site-name" class from the link and only leave the one on the parent (closer to what is in netlify)

2022-04-22 14:23 UTC, donquixote commented
Seems mostly ok.
For the two points that I found I have no final opinion.
Either way we need to rebase.

2022-04-26 15:43 UTC, drishu submitted a review, later dismissed

2022-04-26 16:02 UTC, drishu approved these changes, later dismissed

2022-04-26 22:46 UTC, donquixote reviewed
I am generally ok with the changes but I would wish some response to my questions.

2022-04-26 22:46 UTC, donquixote commented on templates/search/block--oe-whitelabel-search-form.html.twig
> +{% endblock %}
The `{% block %}` is not really useful if we have no wrappers or other elements in the template.
In core, block templates without other stuff don't have `{% block %}`, e.g. `build/core/modules/system/templates/block--system-messages-block.html.twig`.
In whitelabel, we have `templates/overrides/navigation/block--languageswitcherinterfacetext.html.twig`, which does have the `{% block %}` syntax.

The only reason we would keep it is if we want to add wrapper elements or a title in the future, and we want inheriting templates to also get this change. But is this a realistic scenario?

I don't want to be the one who makes the final decision on this.

2022-04-26 22:46 UTC, donquixote commented on templates/overrides/navigation/block--system-branding-block.html.twig
> +            <div class="bcl-header__site-name ps-0 site-name{{ bcl_component_library == 'neutral' ? ' h5 d-inline-block d-lg-none' }}">
The padding-left that we want to suppress with `ps-0` only applies in large viewports where the entire thing is hidden anyway. So do we need the `ps-0` at all?

Here is what I find in the site css (in showcase), coming from BCL:
```css
@media (min-width: 992px) {
    .bcl-header--ec .bcl-header__project.light,.bcl-header__project.light,.ec__header .bcl-header__project.light {
        background:#fff
    }
    .bcl-header__site-name {
        font-weight: 500;
        padding-left: 1.5rem
    }
```

2022-04-26 22:46 UTC, donquixote commented on modules/oe_whitelabel_search/src/Form/SearchForm.php
> +      '#prefix' => '<div class="bcl-search-form__group w-100">',
I think `flex-grow-1` would be more logical here. But `w-100` does the job, so let's keep it.

2022-04-26 22:46 UTC, donquixote commented on templates/overrides/navigation/block--system-branding-block.html.twig
> +            <div class="bcl-header__site-name ps-0 site-name{{ bcl_component_library == 'neutral' ? ' h5 d-inline-block d-lg-none' }}">
I won't block the PR for this, but still would be interested in why we do this.

2022-04-27 09:55 UTC, donquixote commented on modules/oe_whitelabel_search/templates/form--oe-whitelabel-search-form.html.twig
> +<form{{ attributes.addClass('d-flex', 'mt-3', 'mt-lg-0', 'w-100', 'submittable') }}>
The "submittable" is gone. Resolving this.

2022-04-28 23:11 UTC, donquixote commented on templates/overrides/navigation/block--system-branding-block.html.twig
> +            <div class="bcl-header__site-name ps-0 site-name{{ bcl_component_library == 'neutral' ? ' h5 d-inline-block d-lg-none' }}">
Actually the ps-0 is fine here, it is needed for EC header.

2022-04-28 23:12 UTC, donquixote commented
Happy now, but need rebase.

2022-05-02 05:58 UTC, drishu submitted a review, later dismissed

2022-05-02 09:00 UTC, donquixote submitted a review, later dismissed

2022-05-02 09:51 UTC, drishu approved these changes

2022-05-02 09:54 UTC, donquixote approved these changes

2022-05-02 09:54 UTC, merged