OEL-1297: Full viewmode and tests
openeuropa/oe_whitelabel pull request #107
Opened 2022-03-31 00:08 UTC by Maxfire

What it was done:

1. Full viewmode styled, templates created.
2. Pattern assertion tests added.
3. Functional render test added.

2022-03-31 14:09 UTC, donquixote commented on templates/content/node--oe-project--full.html.twig
> +  </h3>
I see a label for participants, but not for contributors.

2022-03-31 14:46 UTC, donquixote requested changes
Some feedback that I want to submit now before I finish the review.

2022-03-31 14:46 UTC, donquixote commented on templates/content/node--oe-project--full.html.twig
> +  </h3>
I see a label for participants, but not for contributors.

2022-03-31 14:46 UTC, donquixote commented on templates/content/node--oe-project--full.html.twig
> +  </h3>
also, for all field labels we need to support cases where the field is empty.
If I create an almost empty project, i see lots of empty h3 being added.

2022-03-31 14:46 UTC, donquixote commented on templates/content/node--oe-project--full.html.twig
> +  </h3>
Could be achieved with a macro perhaps, to render title + content but only if content is not empty.

2022-03-31 14:46 UTC, donquixote commented on templates/content/oe-organisation--default.html.twig
> +
Do we want all these templates under /content/?
Would it not be better to have /node/, /field/, /field-group/ etc?
TBD in chat.

2022-03-31 14:46 UTC, donquixote commented on templates/content/oe-organisation--default.html.twig
> +  {% if _value is not empty %}
The emptiness check is not working.
If you create stakeholders where some of the fields are empty, you get empty html elements.
Use `{% if _value|trim is not empty %}`, that works.

2022-03-31 15:12 UTC, Maxfire commented on templates/content/oe-organisation--default.html.twig
> +
No, it was discussed, please align with Andras and Fra about it.

2022-03-31 15:24 UTC, drishu requested changes

2022-03-31 15:24 UTC, drishu commented on templates/content/field-group-html-element--node--oe-project--group-coordinators.html.twig
> +  attributes: create_attribute().addClass(['mt-3', 'mb-4', 'border-bottom']),
```suggestion
  attributes: create_attribute().addClass(['mt-3', 'mb-4']),
```

2022-03-31 15:24 UTC, drishu commented on templates/content/oe-organisation--default.html.twig
> +{% for _field in elements if _key|first != '#' %}
```suggestion
{% for _field in elements|without('oe_acronym') if _key|first != '#' %}
```
your printing it already above

2022-03-31 15:24 UTC, drishu commented on templates/content/oe-organisation--default.html.twig
> +  {% if elements.oe_acronym is not empty %} {{ elements.oe_acronym }}{% endif %}
wrap the if's around the h4, your gonna get an empty h4 like this if you dont fill in acronim, and its not a mandatory field

2022-03-31 15:24 UTC, drishu commented on templates/content/field-group-html-element--node--oe-project--group-budget.html.twig
> +{% set _items = [] %}
we should have done a field group formatter for this one https://github.com/openeuropa/oe_theme/blob/3.x/modules/oe_theme_content_project/config/install/core.entity_view_display.node.oe_project.full.yml#L76

2022-03-31 15:24 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.info.yml
> +  - drupal:twig_field_value
dont think this is a dependency of the module

2022-03-31 15:24 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +function _oe_whitelabel_extra_project_preprocess_featured_media(&$variables) {
this should have been done with a formatter

2022-03-31 15:24 UTC, drishu commented on tests/src/PatternAssertions/DescriptionListAssert.php
> +    $field_list_container = $crawler->filter('body');
```suggestion
    $field_list_container = $crawler->filter('dl');
```

2022-03-31 15:24 UTC, drishu commented on tests/src/PatternAssertions/InPageNavigationAssert.php
> +    $page_header = $crawler->filter('body');
try to get closer to the wrapper

2022-03-31 15:24 UTC, drishu commented on tests/src/PatternAssertions/ContentBannerAssert.php
> +        '.card-body .mt-4',
drop the mt-4, use such selectors only when there is nothing else to target

2022-03-31 15:30 UTC, Maxfire commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.info.yml
> +  - drupal:twig_field_value
We do for testing.

2022-03-31 16:27 UTC, drishu commented on modules/oe_whitelabel_extra_project/config/overrides/core.entity_view_display.node.oe_project.full.yml
> +    type: daterange_custom
export date format

2022-03-31 16:45 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.info.yml
> +  - drupal:twig_field_value
put the dependency in whitelabel.info.yml

2022-03-31 16:48 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +function _oe_whitelabel_extra_project_preprocess_featured_media(&$variables) {
we discussed we wont do it because we would loose data like the "alt" and the pattern is supposed to receive ImageValueObejct

2022-04-01 01:26 UTC, donquixote commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +  }
To be clear: I don't like this solution at all!
On the one hand, we currently need these lines under every such field group.
On the other hand, it seems wrong to make this the default behavior.

2022-04-01 01:59 UTC, Maxfire commented on tests/src/PatternAssertions/DescriptionListAssert.php
> +    $field_list_container = $crawler->filter('body');
Nope, it won't work like that.

2022-04-01 02:00 UTC, Maxfire commented on tests/src/PatternAssertions/ContentBannerAssert.php
> +        '.card-body .mt-4',
There's nothing else, it won't work otherwise.

2022-04-01 08:07 UTC, drishu requested changes

2022-04-01 08:07 UTC, drishu commented on modules/oe_whitelabel_extra_project/config/install/core.date_format.oe_whitelabel_project_date.yml
> +pattern: d/m/Y
the date format should always be 22 May 2022 (see d F Y news and event)

2022-04-01 08:07 UTC, drishu commented on modules/oe_whitelabel_helper/tests/src/Functional/Plugin/field_group/PatternFormatterTest.php
> + * Test the Description list pattern field group formatter.
```suggestion
 * Test the pattern field group formatter.
```

2022-04-01 08:07 UTC, drishu commented on modules/oe_whitelabel_helper/tests/src/Functional/Plugin/field_group/PatternFormatterTest.php
> +  protected $defaultTheme = 'stark';
whitelabel

2022-04-01 08:07 UTC, drishu commented on modules/oe_whitelabel_helper/tests/src/Functional/Plugin/field_group/PatternFormatterTest.php
> +
remove these lines (I selected multiple)

2022-04-01 08:07 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +function oe_whitelabel_extra_project_preprocess_pattern_description_list(array &$variables): void {
I also dont like this, better to try suggestions for pattern templates and create a template for each group needed, there we can change the attribute.
see https://github.com/openeuropa/oe_theme/commit/2075b9d4748a4f1089df6eb278dfb9d28848949f

2022-04-01 08:10 UTC, drishu commented on templates/content/node--oe-project--full.html.twig
> +  {{ _self.field_with_header(content.oe_cx_impacts) }}
for some reason some of these appear as description list even when empty

2022-04-01 09:21 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +function oe_whitelabel_extra_project_preprocess_pattern_description_list(array &$variables): void {
we discussed we will keep this solution for now

2022-04-01 09:34 UTC, drishu requested changes

2022-04-01 09:34 UTC, drishu commented on templates/content/node--oe-project--full.html.twig
> +</div>
wrap these lines (from inpage_navigation_fields to the last line in a block inpage_navigation_content

2022-04-01 09:34 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> + * Implements hook_preprocess().
```suggestion
 * Implements hook_preprocess() for pattern description_list.
 * explain why..
```

2022-04-01 09:34 UTC, drishu commented on modules/oe_whitelabel_helper/config/schema/oe_whitelabel_helper.schema.yml
> +    classes:
why do we have so many? I see only label and variant in defaultSettings

2022-04-01 11:52 UTC, drishu requested changes
<img width="1332" alt="Screenshot 2022-04-01 at 14 42 28" src="https://user-images.githubusercontent.com/11507647/161258072-25604f2f-6aec-4696-b701-c3d18940d544.png">
Acronym is not in the title anymore, I though we agreed to have it like that

2022-04-01 11:52 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +    'oe_project_dates',
we need project details here

2022-04-01 11:52 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +    'oe_project_participants',
lead contributors is missing

2022-04-01 15:37 UTC, drishu approved these changes

2022-04-01 16:24 UTC, donquixote requested changes

2022-04-01 16:24 UTC, donquixote commented on modules/oe_whitelabel_helper/src/Plugin/field_group/FieldGroupFormatter/PatternFormatterBase.php
> +   *   Pattern fields to be rendered, or an empty array if none.
Document the option to return NULL!
E.g. ", or NULL if the field group should not be displayed at all."

2022-04-01 16:24 UTC, donquixote commented on modules/oe_whitelabel_helper/tests/src/Functional/Plugin/field_group/PatternFormatterTest.php
> +    'field_ui',
It seems we don't need field_ui, and we don't need the permissions related to it.

2022-04-01 16:24 UTC, donquixote commented on modules/oe_whitelabel_helper/tests/src/Functional/Plugin/field_group/PatternFormatterTest.php
> +    $element_selector = 'dl';
The variable seems unnecessary. We can hard-code 'dl'.

2022-04-01 16:24 UTC, donquixote commented on modules/oe_whitelabel_helper/tests/src/Functional/Plugin/field_group/PatternFormatterTest.php
> +    $this->assertSession()->elementExists('css', $element_selector);
```suggestion
    $assert_session->elementsCount('css', 'dl', 1);
```

2022-04-01 16:24 UTC, donquixote commented on templates/content/node--oe-project--full.html.twig
> +  {{ content.group_project_details }}
The group title still shows up even if the group is empty.
But I don't have a quick solution. So let's merge ignore it for now and do a follow up.

2022-04-01 16:27 UTC, donquixote commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +  }
we decided we keep it

2022-04-01 16:40 UTC, donquixote approved these changes

2022-04-01 16:52 UTC, merged