OEL-1246: Integrate oe_list_pages on oe_whitelabel
openeuropa/oe_whitelabel pull request #111
Opened 2022-04-05 08:23 UTC by escuriola

2022-04-08 08:45 UTC, drishu requested changes

2022-04-08 08:45 UTC, drishu commented on modules/oe_whitelabel_list_pages/tests/modules/oe_whitelabel_list_pages_test/README.md
> +# OpenEuropa Whitelabel oe_list_page test
remove this file, the idea of enabling in admin was just to ease your development and our testing

2022-04-08 08:45 UTC, drishu commented on modules/oe_whitelabel_list_pages/tests/modules/oe_whitelabel_list_pages_test/config/install/search_api.server.test.yml
> +name: test
name this something unique to this module so it does not conflict with other

2022-04-08 08:45 UTC, drishu commented on modules/oe_whitelabel_list_pages/tests/modules/oe_whitelabel_list_pages_test/config/install/search_api.index.test_index.yml
> +id: test_index
an unique name pls

2022-04-08 08:45 UTC, drishu commented on modules/oe_whitelabel_list_pages/templates/item-list--oe-list-pages-results.html.twig
> +{#
move all these templates into oe_whitelabel/templates/list_pages

2022-04-08 08:45 UTC, drishu commented on modules/oe_whitelabel_list_pages/templates/node--oe-list-page--full.html.twig
> +  <div class="container mt-md-4-75 mt-4">
remove, we already have the div.container.mt-5 in the page.html.twig, this would add to much whitespace at the top

2022-04-08 08:45 UTC, drishu commented on modules/oe_whitelabel_list_pages/templates/oe-list-pages-selected-facet.html.twig
> +    'label': item.label,
add `'url': item.url,`

2022-04-08 08:45 UTC, drishu commented on modules/oe_whitelabel_list_pages/templates/node--oe-list-page--full.html.twig
> +        {{ content['extra_field_oe_list_page_results:node:oe_list_page'] }}
the pager is broken to some degree
<img width="510" alt="image" src="https://user-images.githubusercontent.com/11507647/162384792-23083f0c-2d58-4c57-b3f2-20ec4b0042d9.png">
please look into, might be some param is not sent the way we need it in oe_list_pages

2022-04-08 08:45 UTC, drishu commented on modules/oe_whitelabel_list_pages/tests/src/Functional/ListPagesTest.php
> +    $page->pressButton('Save');
no need for this, we just want to assert the front functionality and rendering, just create the list page node programatically (I think I left an example of this in the POC, not sure)

2022-04-08 08:45 UTC, drishu commented on modules/oe_whitelabel_list_pages/tests/src/Functional/ListPagesTest.php
> +    $assert_session->elementTextEquals('css', 'span.badge.bg-light', 'number');
the test is ok, but we should organise this better, in order:
1) set up the required stuff (done but create the list node programatically
2) visit the page, start asserting the structure in the list page template:
  2.1) fetch the left side column
  2.2) assert the offcanvas is present, assert the title, facet, filter buttons
  2.3) fetch the right column
  2.4) assert the title, then the listing, that the pager
3) submit the form, assert the badges

all this is mostly already done but it needs a bit more structure

2022-04-08 08:45 UTC, drishu commented on modules/oe_whitelabel_list_pages/tests/src/Functional/ListPagesTest.php
> +    $this->drupalLogin($this->rootUser);
I dont like this, create what you need programatically and use anonymous user

2022-04-11 11:52 UTC, Maxfire commented on modules/oe_whitelabel_list_pages/templates/node--oe-list-page--full.html.twig
> +        {{ content['extra_field_oe_list_page_results:node:oe_list_page'] }}
Exactly, the problem is in the pattern, created an issue to fix it. https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1442

2022-04-11 19:29 UTC, drishu requested changes

2022-04-11 19:29 UTC, drishu commented on templates/list_pages/node--oe-list-page--full.html.twig
> +<article{{ attributes }}>
sorry for the late notice, but we should remove the article tag, the article tag should wrap an individual piece of content, not a listing

2022-04-11 19:29 UTC, drishu commented on modules/oe_whitelabel_list_pages/README.md
> +This module provides list page for oe_whitelabel bundles.
"This module is a theming companion module to the OpenEuropa List Pages component. It provides the logic needed to theme the list pages."
and link the words "OpenEuropa List Pages" to https://github.com/openeuropa/oe_list_pages

2022-04-11 19:29 UTC, drishu commented on modules/oe_whitelabel_list_pages/oe_whitelabel_list_pages.module
> +function oe_whitelabel_list_pages_theme() {
if you moved the template you don't need this anymore

2022-04-11 19:29 UTC, drishu commented on modules/oe_whitelabel_list_pages/tests/src/Functional/ListPagesTest.php
> +  protected function indexItems($index_id) {
remove this and call `use ExampleContentTrait;`, it defined the exact same function

2022-04-11 19:29 UTC, drishu commented on modules/oe_whitelabel_list_pages/tests/src/Functional/ListPagesTest.php
> +        'type' => 'oe_sc_news',
I think its better as a general rule when writing automated tests to no create dependencies to other modules you are developing unless needed (like a decoupling), we should use mulrev_changed or a custom entity. Please create a follow up ticket to improve this in the future. Is ok for now.

2022-04-11 19:29 UTC, drishu commented on modules/oe_whitelabel_list_pages/oe_whitelabel_list_pages.module
> +function oe_whitelabel_form_oe_list_pages_facets_form_alter(&$form, FormStateInterface $form_state, $form_id) {
use the module name as prefix, no need to declare this on behalf of the theme here, we target a form that can be used only in the front end

2022-04-11 19:29 UTC, drishu commented on modules/oe_whitelabel_list_pages/oe_whitelabel_list_pages.module
> +    foreach ($action_classes as $action_class) {
instead of these loops do array_unique(array_merge..

2022-04-12 08:13 UTC, Maxfire commented on modules/oe_whitelabel_list_pages/tests/src/Functional/ListPagesTest.php
> +        'type' => 'oe_sc_news',
Created here, https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1449 thanks.

2022-04-12 10:22 UTC, drishu submitted a review, later dismissed

2022-04-12 10:32 UTC, Maxfire submitted a review, later dismissed

2022-04-12 11:06 UTC, Maxfire approved these changes, later dismissed

2022-04-13 09:06 UTC, drishu approved these changes

2022-04-13 09:36 UTC, Maxfire approved these changes, later dismissed

2022-04-19 19:47 UTC, donquixote commented on modules/oe_whitelabel_list_pages/tests/src/Functional/ListPagesTest.php
> +namespace Drupal\Tests\oe_whitelabel_list_pages_test\FunctionalJavascript;
This is the wrong namespace..
I know this PR is merged, but I don't know another quick and easy way to mention it.
We can fix it some day in the future when we touch this class again.

2022-05-05 09:25 UTC, drishu requested changes

2022-05-05 09:25 UTC, drishu commented on modules/oe_whitelabel_list_pages/README.md
> +This module is a theming companion module to the [OpenEuropa List Pages](https://github.com/openeuropa/oe_list_pages) component. It provides the logic needed to theme the list pages..
what's with the two dots at the end ?

2022-05-05 09:25 UTC, drishu commented on modules/oe_whitelabel_list_pages/oe_whitelabel_list_pages.info.yml
> +description: Provides list pages to Open Whitelabel entities.
not "Open" but OpenEuropa, also the description is wrong, rather "Companion module for the OE List Pages module"

2022-05-05 09:25 UTC, drishu commented on modules/oe_whitelabel_list_pages/tests/modules/oe_whitelabel_list_pages_test/src/EventSubscriber/ListPageAllowedTypesSubscriber.php
> +<?php
as @donquixote pointed out, this is indeed not needed for the test

2022-05-05 09:25 UTC, drishu commented on templates/list_pages/item-list--oe-list-pages-results.html.twig
> + * Available variables:
remove these

2022-05-17 07:09 UTC, drishu approved these changes

2022-05-17 07:10 UTC, Maxfire approved these changes

2022-05-17 07:10 UTC, merged