OEL-1159: Adapt starter content entities to card last changes.
openeuropa/oe_whitelabel pull request #112
Opened 2022-04-05 15:01 UTC by escuriola

https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1159

2022-04-05 17:29 UTC, donquixote commented
Looks good to me!

2022-04-05 19:14 UTC, donquixote commented on modules/oe_whitelabel_starter_event/templates/node--oe-sc-event--teaser.html.twig
> +      content.oe_sc_event_dates,
I suspect that `content.oe_sc_event_dates` contains some element properties that should not be treated as render elements. Use `|field_value` to clean up.
```suggestion
      content.oe_sc_event_dates|field_value,
```

2022-04-06 16:16 UTC, drishu requested changes

2022-04-06 16:16 UTC, drishu commented on modules/oe_whitelabel_starter_event/templates/node--oe-sc-event--teaser.html.twig
> +      content.oe_sc_event_dates,
```suggestion
      content.oe_sc_event_location|field_value,
      content.oe_sc_event_dates|field_value
```

and use **inline address formatter** for the location

2022-04-06 16:52 UTC, drishu approved these changes, later dismissed

2022-04-06 17:20 UTC, drishu approved these changes, later dismissed

2022-04-06 17:21 UTC, drishu commented on modules/oe_whitelabel_starter_event/templates/node--oe-sc-event--teaser.html.twig
> +      content.oe_sc_event_dates,
in the end we wont do it because the address can be quite long, so we need to be able to configure this. Postponed.

2022-04-06 17:35 UTC, drishu approved these changes

2022-04-06 17:49 UTC, donquixote approved these changes

2022-04-06 17:49 UTC, merged