OEL-1421: Fix cosmetic changes.
openeuropa/oe_whitelabel pull request #122
Opened 2022-04-08 14:18 UTC by Maxfire

Fixed cosmetic, tests provided on showcase.

2022-04-11 09:16 UTC, abel-santos-corral requested changes

2022-04-11 09:16 UTC, abel-santos-corral commented on templates/content/node--oe-project--teaser.html.twig
> +{% if image is not empty %}
Consider if it's better to move this below as:
  'image': (image is not empty) ? image|merge({
    'path': image.src,
  }) : {},

2022-04-11 14:34 UTC, abel-santos-corral approved these changes
Approved

2022-04-12 13:16 UTC, drishu requested changes

2022-04-12 13:16 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +      if (isset($node->{$field}) && !empty($node->{$field}->getValue())) {
```suggestion
      if (isset($node->{$field}) && !$node->{$field}->isEmpty()) {
```

2022-04-12 13:16 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +  foreach ($variables['elements']['#fieldgroups'] as $group) {
this is not completely correct, you should target only the groups that are part of the details group

2022-04-12 13:16 UTC, drishu commented on templates/content/node--oe-project--teaser.html.twig
> +{% if content.oe_project_dates|field_value is not empty %}
remove the entire if

2022-04-12 13:16 UTC, drishu commented on templates/content/node--oe-project--teaser.html.twig
> +      content: _content,
we have meta now for this, see the latest card changes
```suggestion
      meta: [
        content.oe_project_dates|field_value
      ],
```

2022-04-12 15:07 UTC, drishu commented on modules/oe_whitelabel_extra_project/oe_whitelabel_extra_project.module
> +  foreach ($variables['elements']['#fieldgroups'] as $group) {
I looked deeper into the issue, the problem is that the html element group prints the title even if the group is empty. So remove this solution, hide the title from the group, implement the old solution but add also striptags before trim. Then the old code works, but you have to add the "Project details" title in the template.

2022-04-12 15:44 UTC, drishu approved these changes

2022-04-13 09:40 UTC, merged