OEL-1453: Consolidate theme regions
openeuropa/oe_whitelabel pull request #125
Opened 2022-04-19 15:25 UTC by escuriola

https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1453

2022-04-20 18:15 UTC, brummbar requested changes
Two minor remarks.

2022-04-20 18:15 UTC, brummbar commented on templates/overrides/page/page.html.twig
>   * - page.navbar_left: Items for the navbar left region (primary menu).
This we don't have anymore, right?

2022-04-20 18:15 UTC, brummbar commented on oe_whitelabel.info.yml
> +  navbar_branding: 'Navbar branding'
Just realised this one now is out of "style": we removed navbar term completely but for this. Let's rename it to "header_branding".

2022-04-21 19:07 UTC, brummbar approved these changes

2022-04-22 10:38 UTC, drishu approved these changes

2022-04-22 11:44 UTC, merged