OEL-1528: Fix whitelabel issues on template, composer and dependencies.
openeuropa/oe_whitelabel pull request #133
Opened 2022-05-05 09:17 UTC by Maxfire

2022-05-06 16:50 UTC, brummbar requested changes
I don't remember anymore the issue with dependencies that originated the ticket, but some of the things done are wrong.

2022-05-06 16:50 UTC, brummbar commented on tests/src/Functional/ContentEventRenderTest.php
> +    'oe_corporate_blocks',
This is a content type test, and we need to manually enable corporate blocks. This is exactly what we should try to avoid and fix. Please revert.

2022-05-06 16:50 UTC, brummbar commented on modules/oe_whitelabel_helper/oe_whitelabel_helper.info.yml
> -  - openeuropa:oe_corporate_blocks
This was correct, why did we remove it?
We need to clean the list of modules to enable manually in the runner, not fix the dependencies here.
Only our own modules, or modules that are not supposed to mandatory, should be enabled manually (which for us is the runner.yml).

2022-05-12 17:40 UTC, brummbar submitted a review, later dismissed

2022-05-13 10:12 UTC, drishu approved these changes

2022-05-13 10:17 UTC, brummbar approved these changes

2022-05-13 10:17 UTC, merged