OEL-1638: Check variable items has facets before trying to modify them to avoid warning.
openeuropa/oe_whitelabel pull request #161
Opened 2022-06-29 09:49 UTC by escuriola

2022-06-30 14:05 UTC, brummbar submitted a review, later dismissed

2022-06-30 16:45 UTC, drishu requested changes

2022-06-30 16:45 UTC, drishu commented on modules/oe_whitelabel_search/oe_whitelabel_search.module
> +    if (empty($item['value']['#type'])) {
I know this works but what we want to check if it is set, not if it is empty, empty checks for more things than we want to
```suggestion
    if (!isset($item['value']['#type'])) {
```

2022-07-01 06:53 UTC, drishu approved these changes

2022-07-04 09:06 UTC, brummbar approved these changes

2022-07-04 09:06 UTC, merged