OEL-1577: Javascript fallback message.
openeuropa/oe_whitelabel pull request #164
Opened 2022-07-04 15:03 UTC by escuriola

2022-07-06 13:02 UTC, donquixote commented on templates/overrides/page/page.html.twig
> +</noscript>
Seem ok to me.
A few changes that we _could_ make to make this easier to override in a custom theme _without_ copying the complete page template:
- Put the text into a variable which can be customized when extending the template.
- Put the `<noscript>` part into a twig block.

Also not 100% sure about the text, e.g. does a visitor see the website as an "application"?

But let's not change any of this for now, instead I let the second reviewer decide.

2022-07-06 13:02 UTC, donquixote commented on templates/overrides/page/page.html.twig
> +</noscript>
Actually, one more thing I notice: The element has an "x" button which obviously does not work.
I don't know if we can fix that.

2022-07-06 13:02 UTC, donquixote commented on templates/overrides/page/page.html.twig
> +    icon: 'exclamation-triangle-fill',
```suggestion
    icon: 'exclamation-triangle-fill',
    dismissible: false,
```
This will remove the defunct close button.

2022-07-06 13:10 UTC, donquixote commented on templates/overrides/page/page.html.twig
> +    message: 'Please enable JavaScript to continue using this application'|t,
```suggestion
    message: 'Please enable JavaScript and reload the page.'|t,
```
Or propose something better.

2022-07-06 13:11 UTC, donquixote commented on templates/overrides/page/page.html.twig
> +</noscript>
After talking with Francesco: Make the block, but no variable. E.g.
```twig
{% block noscript_message %}
  [...]
```

2022-07-06 16:38 UTC, brummbar commented on templates/overrides/page/page.html.twig
> +</noscript>
We could also call the block "noscript" directly.

2022-07-06 17:42 UTC, brummbar requested changes
We should place the warning after the header:

![image](https://user-images.githubusercontent.com/8488617/177610494-3b2f00d0-da4a-482d-a1c8-159679185235.png)

Just after these lines
```
    {{ page.hero }}
    <div class="container mt-md-4-75 mt-4">
      <div class="row">
```

2022-07-11 23:05 UTC, donquixote approved these changes, later dismissed

2022-07-13 09:11 UTC, drishu approved these changes
Approved on behalf of @brummbar

2022-07-13 09:15 UTC, donquixote approved these changes

2022-07-13 09:36 UTC, closed without merging

2022-07-13 09:36 UTC, escuriola commented
Replaced by https://github.com/openeuropa/oe_whitelabel/pull/168/