OEL-1823: Upgrade to BCL 0.24.0
openeuropa/oe_whitelabel pull request #166
Opened 2022-07-08 13:28 UTC by escuriola

2022-07-13 06:26 UTC, drishu requested changes

2022-07-13 06:26 UTC, drishu commented on modules/oe_whitelabel_list_pages/tests/src/Functional/ListPagesTest.php
> +    $title = $offcanvas->find('css', 'h2.offcanvas-title');
```suggestion
    $title = $offcanvas->find('css', '.offcanvas-title');
```

2022-07-13 06:26 UTC, drishu commented on tests/src/Kernel/FacetsFormTest.php
> +    $title = $header->filter('h2.offcanvas-title');
```suggestion
    $title = $header->filter('.offcanvas-title');
```

2022-07-14 14:30 UTC, drishu approved these changes, later dismissed

2022-07-27 09:02 UTC, drishu approved these changes, later dismissed

2022-07-29 09:17 UTC, drishu submitted a review, later dismissed

2022-08-05 07:57 UTC, drishu approved these changes

2022-08-05 08:42 UTC, brummbar approved these changes

2022-08-05 08:42 UTC, merged