OEL-1650: Move Event registration url to links.
openeuropa/oe_whitelabel pull request #172
Opened 2022-08-02 14:07 UTC by drishu

2022-08-03 05:48 UTC, drishu commented on modules/oe_whitelabel_starter_event/oe_whitelabel_starter_event.module
> +  $url = Url::fromUri($registration_url->getValue()[0]['uri']);
if we change cardinality we change this, but for now we assume 1 value

2022-08-04 11:16 UTC, drishu commented on modules/oe_whitelabel_starter_event/oe_whitelabel_starter_event.module
> +      'text-white',
its not in netlify but if I dont the text color is blue

2022-08-05 15:32 UTC, brummbar requested changes

2022-08-05 15:32 UTC, brummbar commented on modules/oe_whitelabel_starter_event/oe_whitelabel_starter_event.module
> +  $url = Url::fromUri($registration_url->getValue()[0]['uri']);
```suggestion
  $url = $registration_url->first()->getUrl();
```

2022-08-05 15:39 UTC, brummbar approved these changes, later dismissed

2022-08-05 15:47 UTC, brummbar approved these changes

2022-08-05 16:05 UTC, merged