OEL-2070: Style the gallery paragraph.
openeuropa/oe_whitelabel pull request #188
Opened 2022-10-25 17:51 UTC by brummbar

2022-10-27 15:18 UTC, drishu requested changes

2022-10-27 15:18 UTC, drishu commented on modules/oe_whitelabel_helper/config/schema/oe_whitelabel_helper.schema.yml
> +field.formatter.settings.oe_whitelabel_helper_gallery:
without fields its not needed, but good to have it even so

2022-10-27 15:18 UTC, drishu commented on modules/oe_whitelabel_paragraphs/oe_whitelabel_paragraphs.module
> +    ConfigImporter::importSingle('module', 'oe_whitelabel_paragraphs', '/config/overrides/', 'core.entity_view_display.paragraph.oe_gallery.default');
the oe_w_pattern_gallery_item displays we also need to import, either here or in the helper

2022-10-27 16:59 UTC, brummbar commented on modules/oe_whitelabel_paragraphs/oe_whitelabel_paragraphs.module
> +    ConfigImporter::importSingle('module', 'oe_whitelabel_paragraphs', '/config/overrides/', 'core.entity_view_display.paragraph.oe_gallery.default');
Fixed.

2022-10-28 09:33 UTC, drishu submitted a review, later dismissed

2022-11-09 09:26 UTC, drishu approved these changes

2022-11-09 09:28 UTC, merged