OEL-1915: Add Date to the Event teaser.
openeuropa/oe_whitelabel pull request #203
Opened 2022-12-19 07:31 UTC by drishu

2022-12-19 11:47 UTC, drishu commented on modules/oe_whitelabel_starter_event/oe_whitelabel_starter_event.module
> +function _oe_whitelabel_starter_event_preprocess_date(array &$variables): void {
I didn't create a formatter (even though I wanted to) because it would use the date_block pattern  and that is not ready for date ranges.

2023-01-06 15:48 UTC, brummbar requested changes

2023-01-06 15:48 UTC, brummbar commented on modules/oe_whitelabel_starter_event/oe_whitelabel_starter_event.module
> +  if (!empty($end) && $start->format('d-m-y') !== $end->format('d-m-y')) {
Is it correct to show the year twice when it's the same?
![image](https://user-images.githubusercontent.com/8488617/211046297-eac035ac-6429-404f-b51e-823e66e5d505.png)
Maybe it's something to ask the designers.

2023-01-13 14:43 UTC, brummbar approved these changes

2023-01-13 14:43 UTC, merged