ELA-650: Link lists.
openeuropa/oe_whitelabel pull request #226
Opened 2023-07-28 13:34 UTC by julien-

2023-08-23 15:02 UTC, brummbar requested changes
Additional remark: the PR uses the listing pattern, which is a listing of cards, but "exploits" the body parameter to render a full view mode in it, card or teaser. 
This is incorrect (but clever ^_^) from a semantic point of view, and causes for example borders in the card while it should not have borders.
I will create another ticket on my board to fix this situation.

2023-08-23 15:02 UTC, brummbar commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/ColumnLinkDisplayPluginBase.php
> +    $id = Html::getUniqueId('columns');
This is not needed here.

2023-08-23 15:02 UTC, brummbar commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/ColumnLinkDisplayPluginBase.php
> +    $form['equal_height'] = [
These options are configurable here, but they don't exist in the default configuration specified above.

2023-08-23 15:02 UTC, brummbar commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/ColumnLinkDisplayPluginBase.php
> +        'bg-light' => $this->t('Light'),
These values are arbitrary. That's why we need a technical analysis before writing code. We need to discuss what is going to be added here, and how.

2023-08-23 15:02 UTC, brummbar commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/CardDisplayPlugin.php
> +      $entity = $link instanceof EntityAwareLinkInterface ? $link->getEntity() : NULL;
All this method is duplicated in the teaser display plugin. This means it should be in a base class.

2023-08-23 15:02 UTC, brummbar commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/CardDisplayPlugin.php
> +        return $items;
This is not a message that we should show to the editors, as they might not have access to the view mode configuration. Maybe we can instead add an error on pre-save?

2023-08-23 15:02 UTC, brummbar commented on composer.json
> +            "drupal/core": {
Why this is needed here? We don't have field definitions.

2023-08-23 15:02 UTC, brummbar commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/ColumnLinkDisplayPluginBase.php
> +      $attributes = new Attribute($item['attributes'] ?? []);
The buildItems() function return entries all wrapped in `['content' => // the build array]` and nothing else, so this will be always empty.

2023-09-19 12:43 UTC, julien- commented on composer.json
> +            "drupal/core": {
You are right. I will make PR to oe_content to update the current used patch

2023-09-19 14:02 UTC, julien- commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/ColumnLinkDisplayPluginBase.php
> +    $form['equal_height'] = [
Fixed

2023-09-19 14:03 UTC, julien- commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/ColumnLinkDisplayPluginBase.php
> +        'bg-light' => $this->t('Light'),
This values are HTML classes used by OE Whitelabel.

2023-09-19 14:22 UTC, julien- commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/ColumnLinkDisplayPluginBase.php
> +      $attributes = new Attribute($item['attributes'] ?? []);
I let the possibility to alter / create custom DisplayPlugin

2023-09-19 14:23 UTC, julien- commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/CardDisplayPlugin.php
> +      $entity = $link instanceof EntityAwareLinkInterface ? $link->getEntity() : NULL;
YES ... I will move it to parent ColumnLinkDisplayPluginBase class. Do you agree with that ?

2023-09-19 14:26 UTC, julien- commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/CardDisplayPlugin.php
> +        return $items;
The best way is to not offer the possibility to select a non-existent ViewDisplay but we know we have an issue between Source and Display ... I will go with a validate()

2023-10-17 15:57 UTC, brummbar requested changes
If patches from other components are needed, they must be added in the composer.json.

I'm still conflicted about the equal height and background classes.

2023-10-17 15:57 UTC, brummbar commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/CardDisplayPlugin.php
> +  }
This doesn't need to be here since we don't use it.

2023-10-17 15:57 UTC, brummbar commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/ColumnLinkDisplayPluginBase.php
> +        \Drupal::messenger()->addError($message);
We need to move this code to a validation when the link list is saved.

2023-10-17 15:57 UTC, brummbar commented on modules/oe_whitelabel_link_lists/src/Plugin/LinkDisplay/ColumnLinkDisplayPluginBase.php
> +        'bg-light' => $this->t('Light'),
It's not ok to store classes as content. Also, this is limiting. Let's remove equal height and background color from this one. They have to be extensions on the project for now.

2024-01-03 14:31 UTC, julien- commented
Done in #239

2024-01-03 14:31 UTC, closed without merging