OEL-543: Styling components.
openeuropa/oe_whitelabel pull request #27
Opened 2021-10-05 16:06 UTC by escuriola

Jira issue:
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-543?

2021-10-08 09:41 UTC, abel-santos-corral approved these changes, later dismissed
Reviewed. Checked that all changes required at ticket were on place on the form at search page.

2021-10-11 11:28 UTC, drishu requested changes

2021-10-11 11:28 UTC, drishu commented on oe_whitelabel.theme
> +function oe_whitelabel_form_alter(&$form, FormStateInterface $form_state, $form_id) {
I'm thinking that adding classes might change other forms in ways we might not want, lets use hook_form_FORM_ID_alter to target the facets form specifically

2021-10-11 11:28 UTC, drishu commented on oe_whitelabel.theme
> +    $form['actions']['submit']['#attributes']['class'] = array_unique($form['actions']['submit']['#attributes']['class']);
the browser can handle duplicates, if there are many, then the source of the duplication needs to be fixed

2021-10-11 11:28 UTC, drishu commented on oe_whitelabel.theme
> +    $form['actions']['reset']['#attributes']['class'] = array_unique($form['actions']['reset']['#attributes']['class']);
the browser can handle duplicates, if there are many, then the source of the duplication needs to be fixed

2021-10-15 14:17 UTC, drishu requested changes
- we now have oe_whitelabel_search, we should move this widget into there
- add a kernel test for the widget

2021-10-15 14:17 UTC, drishu commented on composer.json
> +        "drupal/better_exposed_filters": "^5.0@beta",
I don't think this should be a hard requirement, rather require-dev

2021-10-15 14:17 UTC, drishu commented on modules/oe_whitelabel_helper/src/Plugin/better_exposed_filters/sort/FloatEndSortWidget.php
> + *   id = "float_end_sort",
prefix with oe_whitelabel

2021-10-15 14:17 UTC, drishu commented on modules/oe_whitelabel_helper/src/Plugin/better_exposed_filters/sort/FloatEndSortWidget.php
> + *   label = @Translation("Float End Sort Better Exposed Filter"),
```suggestion
 *   label = @Translation("Float End Sort"),
```

2021-10-18 14:44 UTC, drishu submitted a review, later dismissed

2021-10-18 16:27 UTC, drishu submitted a review, later dismissed

2021-10-18 16:31 UTC, drishu approved these changes

2021-10-18 16:37 UTC, GilNovacomm approved these changes

2021-10-18 18:22 UTC, merged