OEL-1771: Moved patterns tests from oe_whitelabel.
openeuropa/oe_whitelabel pull request #273
Opened 2024-05-13 13:16 UTC by tibi2303

2024-05-17 07:26 UTC, AaronGilMartinez requested changes
Changes seems right but to make sure we need drone green and conflicts solved.

To get changes from oe_bootstrap_theme branch you can do:
`composer require openeuropa/oe_bootstrap_theme:"dev-OEL-1771"`

And then test all together, when bootstrap is released we can change composer to get new version.

Can you check both, please?

2024-05-27 07:32 UTC, drishu requested changes

2024-05-27 07:32 UTC, drishu commented on composer.json
> +        "openeuropa/oe_bootstrap_theme": "^1.10.0"
if you need to upgrade then best to do as @AaronGilMartinez instructed

2024-05-28 18:01 UTC, tibi2303 commented on composer.json
> +        "openeuropa/oe_bootstrap_theme": "^1.10.0"
tried but it failed:
https://drone.fpfis.eu/openeuropa/oe_whitelabel/2098/15

https://github.com/openeuropa/oe_whitelabel/pull/273/commits/229a46b428035c32f4c4efb03f7bf244bdca0b40

Fra helped me out to patch and update to this version. I am not sure if we should keep it or not.

2024-05-29 11:09 UTC, drishu commented on composer.json
> +                "new pattern assert": "https://github.com/openeuropa/oe_bootstrap_theme/compare/1.10.0...OEL-1771.patch"
```suggestion
                "new pattern assert": "https://github.com/openeuropa/oe_bootstrap_theme/compare/1.10.0...OEL-1771.diff"
```

2024-05-29 12:20 UTC, tibi2303 commented on composer.json
> +                "new pattern assert": "https://github.com/openeuropa/oe_bootstrap_theme/compare/1.10.0...OEL-1771.patch"
doen

2024-05-29 12:46 UTC, drishu submitted a review, later dismissed

2024-05-30 06:54 UTC, AaronGilMartinez approved these changes

2024-05-30 06:59 UTC, drishu approved these changes

2024-05-30 06:59 UTC, merged