OEL-2604: Change alignment of the sorting options
openeuropa/oe_whitelabel pull request #278
Opened 2024-05-31 15:48 UTC by AaronGilMartinez

2024-06-03 06:45 UTC, drishu requested changes
I dont think a change in the template is needed, I think its rather a css issue.
If I remove `.oe-list-pages-sort-form .form-item{margin:0 0 0 1.5rem}` for instance then it looks ok above the 1200px breakpoint
And then some work on the sort label's and select's margins are needed.

On other list pages its ok because the sort option are smaller, so what if we get much longer ones?

2024-06-03 11:31 UTC, drishu approved these changes, later dismissed

2024-06-03 15:10 UTC, brummbar requested changes

2024-06-03 15:10 UTC, brummbar commented on resources/sass/components/_list_pages.scss
> +  @media (min-width: 576px) {
This is not working:
![image](https://github.com/openeuropa/oe_whitelabel/assets/8488617/2f9ffb45-bfd1-49f0-acbc-d9c651df161b)

2024-06-05 15:17 UTC, drishu requested changes

2024-06-05 15:17 UTC, drishu commented on resources/sass/components/_list_pages.scss
> +  .form-label {
dont think this is ok, and its worse for me now, see
![Screenshot 2024-06-05 at 18 15 43](https://github.com/openeuropa/oe_whitelabel/assets/11507647/1f7687e8-f569-4dda-b4a5-e2adbb824f09)

2024-06-19 15:30 UTC, drishu approved these changes, later dismissed
The solution looks better now

2024-06-24 16:39 UTC, brummbar commented
Still has some issues on some viewports:
![image](https://github.com/openeuropa/oe_whitelabel/assets/8488617/7087d963-df04-454d-8e0c-d47b831b1ebe)

2024-06-28 15:13 UTC, AaronGilMartinez reviewed
Approving, can't approve my own PR

2024-07-12 11:13 UTC, brummbar approved these changes

2024-07-12 11:13 UTC, merged