OEL-534: Counter to 0 included in the template.
openeuropa/oe_whitelabel pull request #28
Opened 2021-10-06 11:31 UTC by Maxfire

Fixes:
 - https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-534

2021-10-07 13:20 UTC, abel-santos-corral submitted a review, later dismissed
Reviewed and tested. When no element is found the total live summary is set to 0 instead of empty.

2021-10-11 12:02 UTC, drishu requested changes

2021-10-11 12:02 UTC, drishu commented on templates/overrides/search/facets-summary-count.html.twig
> +{% set count = count ?? 0 %}
if the result from our live total is 0 when it should be, then there is not point in this check

2021-10-11 14:42 UTC, drishu approved these changes

2021-10-11 14:43 UTC, abel-santos-corral approved these changes

2021-10-11 14:44 UTC, merged