OEL-450: Theme the site branding block.
openeuropa/oe_whitelabel pull request #3
Opened 2021-09-06 16:23 UTC by abel-santos-corral

Add twig to override block--system-branding-block and add classes to it.

2021-09-07 15:02 UTC, escuriola submitted a review, later dismissed

2021-09-08 07:05 UTC, drishu requested changes

2021-09-08 07:05 UTC, drishu commented on tests/Functional/SiteBrandingBlockTest.php
> +<?php
Don't use a functional test just to check some classes and/or markup.
Please use something similar to https://github.com/openeuropa/oe_theme/blob/2.x/tests/Kernel/RenderingTest.php#L103

2021-09-08 10:24 UTC, drishu commented on tests/Functional/SiteBrandingBlockTest.php
> +<?php
in the end that one was incompatible with blocks

2021-09-08 10:25 UTC, drishu approved these changes

2021-09-08 10:29 UTC, escuriola approved these changes

2021-09-08 10:31 UTC, merged