OEL-3418: Changed list title for listing and search.
openeuropa/oe_whitelabel pull request #317
Opened 2024-10-04 17:11 UTC by tibi2303

2024-10-07 10:41 UTC, AaronGilMartinez approved these changes, later dismissed

2024-10-08 07:55 UTC, drishu requested changes

2024-10-08 07:55 UTC, drishu commented on templates/list_pages/node--oe-list-page--full.html.twig
> -          <h4 class="mb-0">
it is ok to fix the tags, but we are breaking the page visually, we need to ensure that it looks as before

2024-10-09 08:21 UTC, drishu approved these changes

2024-10-09 10:15 UTC, merged