OEL-3503: Support slim select V2
openeuropa/oe_whitelabel pull request #331
Opened 2024-12-09 09:19 UTC by piotrsmykaj

2025-01-01 13:17 UTC, drishu requested changes

2025-01-01 13:17 UTC, drishu commented on modules/oe_whitelabel_helper/oe_whitelabel_helper.module
> +    $version = \Drupal::config('slim_select.settings')->get('version');
Let's move all sim select code into a class under /source SlimSelectProcess (or if u have a better idea). Mark it as internal. Also this part that you added for version 2 repeats, so you can add it into a private method.

2025-01-01 13:17 UTC, drishu commented on modules/oe_whitelabel_helper/oe_whitelabel_helper.module
> +    if (str_starts_with($version, '2.')) {
the saved version starts with v
```suggestion
    if (str_starts_with($version, 'v2.')) {
```

2025-01-07 16:04 UTC, piotrsmykaj commented on modules/oe_whitelabel_helper/oe_whitelabel_helper.module
> +    $version = \Drupal::config('slim_select.settings')->get('version');
ok please check my changes.

2025-01-13 17:14 UTC, drishu requested changes

2025-01-13 17:14 UTC, drishu commented on modules/oe_whitelabel_helper/src/SlimSelectHelper.php
> +      $path = \Drupal::service('oe_whitelabel_helper.slim_select')->getJsFilePath();
```suggestion

```

2025-01-13 17:14 UTC, drishu commented on modules/oe_whitelabel_helper/src/SlimSelectHelper.php
> +          ':path' => $path,
```suggestion
          ':path' => $this->getJsFilePath(),
```

2025-01-13 17:14 UTC, drishu commented on modules/oe_whitelabel_helper/src/SlimSelectHelper.php
> +    $path = \Drupal::service('oe_whitelabel_helper.slim_select')->getJsFilePath();
```suggestion

```

2025-01-13 17:14 UTC, drishu commented on modules/oe_whitelabel_helper/src/SlimSelectHelper.php
> +      $path => [
```suggestion
      $this->getJsFilePath() => [
```

2025-01-13 17:14 UTC, drishu commented on modules/oe_whitelabel_helper/src/SlimSelectHelper.php
> +  public function alterRequirements(array &$requirements) {
```suggestion
  public function alterRequirements(array &$requirements): void {
```

2025-01-13 17:14 UTC, drishu commented on modules/oe_whitelabel_helper/src/SlimSelectHelper.php
> +  public function libraryInfoAlter(array &$libraries, string $extension) {
```suggestion
  public function libraryInfoAlter(array &$libraries, string $extension): void {
```

2025-01-13 17:14 UTC, drishu commented on modules/oe_whitelabel_helper/src/SlimSelectHelper.php
> +  private function getJsFilePath() {
```suggestion
  private function getJsFilePath(): string {
```

2025-01-13 17:14 UTC, drishu commented on modules/oe_whitelabel_helper/src/SlimSelectHelper.php
> +    $theme_handler = \Drupal::service('theme_handler');
here we need to use injection here, let the class implement ContainerInjectionInterface and the classResolver will take care

2025-01-13 17:14 UTC, drishu commented on modules/oe_whitelabel_helper/oe_whitelabel_helper.services.yml
> +  oe_whitelabel_helper.slim_select:
A few thoughts about this:
-  services should be reusable classes (as in can be used anywhere), this class is specific for the requirements alter and the info alter, so it is not suited for a service.
- we dont want this to be used as like an api so it should have been marked with `public: false` but that brings a whole different set of problems when trying to use in a preprocess, so I think we should drop the service part.

We still want code reuse and OOP so I thought more along the lines of a helper class in oe_whitelabel/src (see we have 2 more there), And then we call the class with \Drupal::classResolver(SlimSelectHelper::class);

2025-01-28 16:41 UTC, piotrsmykaj commented on src/SlimSelectHelper.php
> +    return '';
@drishu I added the condition to check if the theme exists.

2025-01-28 16:42 UTC, piotrsmykaj commented on modules/oe_whitelabel_helper/oe_whitelabel_helper.services.yml
> +  oe_whitelabel_helper.slim_select:
oky good idea, it's done

2025-01-28 16:42 UTC, piotrsmykaj commented on modules/oe_whitelabel_helper/src/SlimSelectHelper.php
> +    $theme_handler = \Drupal::service('theme_handler');
done

2025-02-03 15:57 UTC, drishu requested changes
I'm stopping my review here as I found a blocking issue for me. I've created and used a tag for oebt 0.3503.202502031520, so that I have the assets built, and indeed the slimselect 2 folder is present, but when I create a multiselect field I get this:
![image](https://github.com/user-attachments/assets/b91e845a-f6fb-4310-b33b-8adf4ec62864)

I've asked @tibi2303 to look into the bcl releases but something is defenetly wrong.

2025-02-03 15:57 UTC, drishu commented on oe_whitelabel.theme
> +  \Drupal::service('oe_whitelabel_helper.slim_select')->libraryInfoAlter($libraries, $extension);
\Drupal::classResolver

2025-02-03 15:57 UTC, drishu commented on src/SlimSelectHelper.php
> +    $this->themeHandler = $themeHandler;
Lets go for the modern property promotion

2025-02-04 16:17 UTC, piotrsmykaj commented on oe_whitelabel.theme
> +  \Drupal::service('oe_whitelabel_helper.slim_select')->libraryInfoAlter($libraries, $extension);
done

2025-02-04 16:22 UTC, piotrsmykaj commented
> I'm stopping my review here as I found a blocking issue for me.

<img width="340" alt="image" src="https://github.com/user-attachments/assets/5fcca4d4-2662-42a7-89fd-f9b9b661de20" />

@drishu @tibi2303 with BCL 0.3501.202502031900 it looks on my local as you can see on the screenshot above. At the HEH project, we applied some customizations and arrows seems fine with it: https://git.fpfis.tech.ec.europa.eu/ep/ep-historia-museum-dev/-/blob/master/lib/themes/ep_historia_museum/src/scss/components/bcl_theme/_multiselect.scss?ref_type=heads#L44

2025-02-06 15:50 UTC, drishu approved these changes
Approved, lets not forget to update oebt before merge

2025-02-10 08:26 UTC, drishu submitted a review, later dismissed

2025-03-04 15:28 UTC, drishu approved these changes

2025-03-04 15:28 UTC, merged