OEL-453: [oe_whitelabel] authentication
openeuropa/oe_whitelabel pull request #6
Opened 2021-09-09 12:45 UTC by abel-santos-corral

- [OEL-453](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-453)

2021-09-09 14:13 UTC, drishu requested changes

2021-09-09 14:13 UTC, drishu commented on tests/src/Kernel/AuthenticationBlockTest.php
> + * Tests the Site Branding Block rendering.
```suggestion
 * Tests the OE Authentication LoginBlock rendering.
```

2021-09-09 14:13 UTC, drishu commented on tests/src/Kernel/AuthenticationBlockTest.php
> +
remove this newline

2021-09-09 14:13 UTC, drishu commented on tests/src/Kernel/AuthenticationBlockTest.php
> +    $this->assertCount(1, $actual);
check for the icon please

2021-09-12 08:42 UTC, drishu approved these changes

2021-09-13 06:43 UTC, escuriola approved these changes

2021-09-13 06:43 UTC, Maxfire approved these changes
approved :+1:

2021-09-13 06:47 UTC, merged