OEL-1147: Footer refactor
openeuropa/oe_whitelabel pull request #69
Opened 2022-02-11 12:36 UTC by escuriola

2022-02-17 13:38 UTC, drishu requested changes

2022-02-17 13:38 UTC, drishu commented on modules/oe_whitelabel_helper/src/Plugin/Block/NeutralFooterBlock.php
> +class NeutralFooterBlock extends FooterBlockBase implements ContainerFactoryPluginInterface {
I like the block, but now our helper module is now using (depending on) classes from oe_corporate_blocks, so add the dependency to its info file

2022-02-17 13:38 UTC, drishu commented on modules/oe_whitelabel_helper/src/TwigExtension/TwigExtension.php
>        new TwigFunction('bcl_block', [$this, 'bclBlock']),
I think this is a good occasion to deprecate bcl_block and use twig_tweak::drupal_block

2022-02-17 13:38 UTC, drishu commented on modules/oe_whitelabel_helper/src/TwigExtension/TwigExtension.php
> +    $title = \Drupal::translation()->translate($title)->render();
with or without this line, same result

2022-02-17 13:38 UTC, drishu commented on modules/oe_whitelabel_helper/src/TwigExtension/TwigExtension.php
> +    return ['#markup' => '<p class="' . $classes . '">' . $title . '</p>'];
Since this is used in twig we can use https://www.drupal.org/node/2311123, BUT the real question is: why not use a macro ?
When the function just wraps stuff into html then its a good candidate for a macro
```
{% macro bcl_title(title, classes) %}
  <p class="{{ classes }}">{{ title }}</p>
{% endmacro %}
```

2022-02-17 13:38 UTC, drishu commented on oe_whitelabel.theme
> +    '#default_value' => theme_get_setting('component_library') ?? 'eu',
```suggestion
    '#default_value' => theme_get_setting('component_library') ?? 'neutral',
```
Let's default to neutral, this way we bring to the attention of the site builders that they have to chose a flavour

2022-02-17 13:38 UTC, drishu commented on modules/oe_whitelabel_helper/src/Plugin/Block/NeutralFooterBlock.php
> +    $config = $this->configFactory->get('oe_corporate_blocks.ec_data.footer');
do we know what data (links) need to be loaded for the neutral block ? I hear neutral is for agencies so EC looks good at first glance

2022-02-17 15:12 UTC, escuriola commented on modules/oe_whitelabel_helper/src/Plugin/Block/NeutralFooterBlock.php
> +    $config = $this->configFactory->get('oe_corporate_blocks.ec_data.footer');
Not yet, but yes, EC is really similar to neutral in several things

2022-02-18 12:05 UTC, drishu requested changes
The reason drone is failing in lowest is d9 is installed instead of d8, try a rebase

2022-02-18 12:05 UTC, drishu commented on modules/oe_whitelabel_helper/src/TwigExtension/TwigExtension.php
> -      new TwigFunction('bcl_block', [$this, 'bclBlock']),
if we remove it we have to remove also the bclBlock method, but don't do that yet, just mark it as [deprecated](https://www.drupal.org/docs/develop/standards/api-documentation-and-comment-standards#deprecated)

2022-02-22 07:58 UTC, drishu requested changes

2022-02-22 07:58 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-eu-footer.html.twig
> +          'content': drupal_block('whitelabel_eu_logo_block'),
you are deleting the logos in the header refactor so you need to add the logo directly

2022-02-22 11:18 UTC, merged