OEL-1160: Header refactor.
openeuropa/oe_whitelabel pull request #71
Opened 2022-02-16 17:31 UTC by escuriola

https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1060

2022-02-22 07:47 UTC, drishu requested changes
Somethings not right in mobile view
<img width="311" alt="Screenshot 2022-02-22 at 09 44 35" src="https://user-images.githubusercontent.com/11507647/155085999-a0a3a455-da31-42f7-b428-33a17de5e349.png">

2022-02-22 07:47 UTC, drishu commented on modules/oe_whitelabel_helper/src/EuropeanUnionLanguages.php
> + * Helper class storing European Union languages information.
add a @see so people will know where this came from

2022-02-22 07:47 UTC, drishu commented on modules/oe_whitelabel_helper/src/TwigExtension/TwigExtension.php
> +  public function toInternalLanguageId($language_code): string {
```suggestion
  public function toInternalLanguageId(string $language_code): string {
```

2022-02-22 07:47 UTC, drishu commented on oe_whitelabel.theme
> +      // Check whether ECL provides a logo for the language.
```suggestion
      // Check whether BCL provides a logo for the language.
```

2022-02-22 07:47 UTC, drishu commented on tests/src/Kernel/SiteBrandingBlockTest.php
> +
remove newline

2022-02-22 07:47 UTC, drishu commented on oe_whitelabel.theme
> +      $variables['current_language_id'] = 'no';
not saying this is wrong, but do double check the Norwegian logo name

2022-02-23 08:27 UTC, drishu requested changes
Don't forget to add the new tag for the new logo location in OEBT

2022-02-23 08:27 UTC, drishu commented on oe_whitelabel.theme
> +  $variables['bcl_logo_path'] = base_path() . drupal_get_path('theme', 'oe_bootstrap_theme') . '/assets/logos/';
since we'r not using the old logo path anymore we should delete modules/oe_whitelabel_helper/images/

2022-02-23 08:27 UTC, drishu commented on templates/overrides/navigation/block--system-branding-block.html.twig
> +  <!-- project name -->
Let's rather use twig comments
```suggestion
  {# Project name. #}
```
The idea is that these get printed inside the page and take bandwidth, its not much but it adds up

2022-02-23 08:27 UTC, drishu commented on modules/oe_whitelabel_helper/src/Plugin/Block/CorporateEcLogoBlock.php
> -<?php
with these gone, we should remove block--whitelabel-ec-logo-block.html.twig same for eu

2022-02-23 08:27 UTC, drishu commented on templates/overrides/navigation/block--system-branding-block.html.twig
> +{% set light = bcl_header_style == 'light' %}
I see a lot of empty lines and intendation, I think its a good candidate for `{% apply spaceless %}`

2022-02-23 08:27 UTC, drishu commented on templates/overrides/navigation/block--system-branding-block.html.twig
> +            {{- _site_name -}}
if you will add `apply spaceless` you wont need the other whitespace filters
```suggestion
            {{ _site_name }}
```

2022-02-23 08:27 UTC, drishu commented on templates/overrides/page/page.html.twig
> +      <!-- navbar -->
use twig comments

2022-02-23 08:27 UTC, drishu commented on templates/overrides/page/page.html.twig
> +      <!-- breadcrumbs -->
use twig comments

2022-02-23 08:27 UTC, drishu commented on templates/overrides/page/page.html.twig
>      <div class="container mt-2">
phpstorm is complaing about unclosed divs, lets improve this and toggle the mt class instead of the entire div

2022-02-23 08:27 UTC, drishu commented on tests/src/Functional/CorporateHeaderLogosTest.php
> +    // Create a user that does have permission to administer theme settings.
```suggestion
    // Create a user that has permission to administer theme settings.
```

2022-02-23 08:27 UTC, drishu commented on tests/src/Functional/CorporateHeaderLogosTest.php
> +    // Visit theme administration page.
remove this comment, its obvious

2022-02-23 08:27 UTC, drishu commented on tests/src/Functional/CorporateHeaderLogosTest.php
> +
remove newline

2022-02-23 08:27 UTC, drishu commented on tests/src/Functional/CorporateHeaderLogosTest.php
> +    // Select EU component library and save configuration.
move this comment above drupalGet

2022-02-23 08:27 UTC, drishu commented on tests/src/Functional/CorporateHeaderLogosTest.php
> +    // Visit theme administration page.
same, remove this, move the other comment up and remove newline

2022-02-23 08:27 UTC, drishu commented on tests/src/Functional/CorporateHeaderLogosTest.php
> +  protected $defaultTheme = 'stark';
```suggestion
  protected $defaultTheme = 'oe_whitelabel';
```

2022-02-23 08:27 UTC, drishu commented on tests/src/Functional/CorporateHeaderLogosTest.php
> +    \Drupal::service('theme_installer')->install(['oe_whitelabel']);
remove these, we can just use the `$defaultTheme`

2022-02-23 08:27 UTC, drishu commented on tests/src/Kernel/SiteBrandingBlockTest.php
> +    \Drupal::state()->set('bcl_component_library', 'eu');
remove this;
and this `$this->container->set('theme.registry', NULL);`

2022-02-23 08:27 UTC, drishu commented on tests/src/Kernel/SiteBrandingBlockTest.php
> +    drupal_static_reset('theme_get_setting');
remove this

2022-02-23 08:27 UTC, drishu commented on tests/src/Kernel/SiteBrandingBlockTest.php
>        ->getStorage('block');
instead of entity->create entity->save we can now do
```
$entity = $entity_type_manager->load('oe_whitelabel_branding');
```
as we now have the block exported

2022-02-23 08:27 UTC, drishu commented on tests/src/Kernel/SiteBrandingBlockTest.php
> +    $this->assertCount(1, $link);
the test looks good to me, we test the branding structure and rendering, it's clean and clear, but, I have a suggestion, now that we have `CorporateHeaderLogosTest` we could rename it to `CorporateHeaderTest` and test the entire header section there with neutral, ec, eu.
It's just a suggestion, I don't insist, perhaps even discuss with @brummbar

2022-02-23 16:10 UTC, drishu submitted a review, later dismissed

2022-02-23 16:59 UTC, drishu requested changes

2022-02-23 16:59 UTC, drishu commented on templates/overrides/navigation/block--system-branding-block.html.twig
> +              light ? 'text-dark': 'text-white',
something like this needs to be added also to the title printed in mobile, see
<img width="311" alt="Screenshot 2022-02-23 at 18 58 24" src="https://user-images.githubusercontent.com/11507647/155368434-61b9aaf5-0735-46ce-b635-de24cc5f54d2.png">
(I also see a strange line there)

2022-02-24 11:37 UTC, drishu approved these changes, later dismissed

2022-03-02 20:34 UTC, brummbar requested changes

2022-03-02 20:34 UTC, brummbar commented on oe_whitelabel.theme
> +    $variables['logo_aria_label'] = t('Home') . ' - ' . t('European Commission');
```suggestion
    $variables['logo_aria_label'] = t('Home - European Commission');
```

2022-03-02 20:34 UTC, brummbar commented on oe_whitelabel.theme
> +    $variables['logo_aria_label'] = t('Home') . ' - ' . t('European Union');
```suggestion
    $variables['logo_aria_label'] = t('Home - European Union');
```

2022-03-02 20:34 UTC, brummbar commented on templates/overrides/navigation/block--system-branding-block.html.twig
> +            <a {{ create_attribute().addClass(img_classes).setAttribute('rel', 'Home') }} href="{{ path('<front>') }}">
```suggestion
            <a class="d-none d-lg ...." href="{{ path('<front>') }}">
```
Rel attribute I didn't find a value for home https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel

2022-03-02 20:34 UTC, brummbar commented on templates/overrides/navigation/region--navbar-right.html.twig
> +  <ul{{ attributes }}>
Wait, region content inside a ul tag? This is weird.

2022-03-02 20:34 UTC, brummbar commented on templates/overrides/page/page.html.twig
> +    <header {{ attributes }}>
Just output in the header tag.

2022-03-02 20:34 UTC, brummbar commented on templates/overrides/page/page.html.twig
> +    <div class="container {{ page.header ? 'mt-2': 'mt-5' }} ">
```suggestion
    <div class="container {{ page.header ? 'mt-2': 'mt-5' }}">
```

2022-03-02 20:34 UTC, brummbar commented on tests/src/Kernel/SiteBrandingBlockTest.php
> +    $crawler = new Crawler($render->__toString());
```suggestion
    $crawler = new Crawler((string) $render);
```

2022-03-02 20:34 UTC, brummbar commented on templates/overrides/navigation/region--navbar-right.html.twig
> + * Default theme implementation to display a region.
Please update this. Write which template we are overriding too.

2022-03-02 20:34 UTC, brummbar commented on templates/overrides/navigation/block--system-branding-block.html.twig
> +      <div {{ create_attribute().addClass(project_classes) }}>
```suggestion
      <div class="bcl-header__project{{ light is not empty ? ' light' }}">
```

2022-03-02 20:34 UTC, brummbar commented on templates/overrides/navigation/block--system-branding-block.html.twig
> +        </div>
Don't abuse attributes, if you can just output in html.

2022-03-09 18:51 UTC, brummbar submitted a review, later dismissed
Looks good, let's rebase and merge.

2022-03-11 16:57 UTC, brummbar submitted a review, later dismissed
Looks good now.

2022-03-14 09:55 UTC, drishu approved these changes

2022-03-14 10:01 UTC, drishu requested changes
Lets add the diff to 1.x in composer

2022-03-14 10:20 UTC, drishu approved these changes

2022-03-14 10:53 UTC, brummbar approved these changes

2022-03-14 10:54 UTC, merged