OEL-1133: Contact form theming and testing provided.
openeuropa/oe_whitelabel pull request #73
Opened 2022-02-17 14:39 UTC by Maxfire

Theming for contact form and testing done.

2022-02-18 08:36 UTC, drishu requested changes

2022-02-18 08:36 UTC, drishu commented on modules/oe_whitelabel_helper/oe_whitelabel_helper.module
> +
the helper module is for general purpose code like field formatters, helper functions so on, this should go into ints own submodule oe_whitelabel_contact_forms, enable the new module in the runner.yml and provide a second PR that enables the new module in oe_showcase.info.yml and replace this line https://github.com/openeuropa/oe_showcase/blob/EPIC-1136-contact_solution/modules/oe_showcase_contact_forms/oe_showcase_contact_forms.info.yml#L8 with the new module.
The new module will require (have dependencies on) oe_contact_forms of course and describe in the info file that openeuropa/oe_contact_forms needs to be added in composer.

2022-02-18 08:36 UTC, drishu commented on composer.json
> +        "openeuropa/rdf_skos": "~1.0",
remove this, we already have it here https://github.com/openeuropa/oe_contact_forms/blob/master/composer.json#L14

2022-02-18 08:36 UTC, drishu commented on composer.json
> +        "openeuropa/oe_corporate_countries": "~2.0"
remove this, we already have it here https://github.com/openeuropa/oe_contact_forms/blob/master/composer.json#L15

2022-02-18 08:36 UTC, drishu commented on modules/oe_whitelabel_helper/oe_whitelabel_helper.module
> +    '#weight' => 6,
this is not good, becasue if I add 6 fields through the UI then it wont appear in the right place, rather add a wrapping element, like a fieldset or whatever and add the hr to it, then move the elements 'copy', 'privacy_policy', 'actions' into it, and set the wrapper weight to a higher number so it is always on the bottom

2022-02-18 08:36 UTC, drishu commented on modules/oe_whitelabel_helper/oe_whitelabel_helper.module
> +      if (strpos($contact_form_field->getName(), 'field_') === 0) {
this way is unreliable, the correct way of checking if a field is a managed field and not a base field is by checking the definition
```suggestion
      if (!$contact_form_field->getFieldDefinition() instanceof FieldConfigInterface){
        continue;
      }
      $fields[] = $contact_form_field->getName();
```

2022-02-18 16:19 UTC, drishu requested changes

2022-02-18 16:19 UTC, drishu commented on modules/oe_whitelabel_contact_forms/README.md
> +```
```suggestion
```json
```

2022-02-18 16:19 UTC, drishu commented on modules/oe_whitelabel_contact_forms/oe_whitelabel_contact_forms.module
> + * Implements hook_form_FORM_ID_alter().
```suggestion
 * Implements hook_form_FORM_ID_alter() for contact_message_form().
```

2022-02-18 16:19 UTC, drishu commented on modules/oe_whitelabel_contact_forms/tests/src/Kernel/ContactFormRenderTest.php
> +    $this->container->set('theme.registry', NULL);
no need for this

2022-02-18 16:19 UTC, drishu commented on modules/oe_whitelabel_contact_forms/tests/src/Kernel/ContactFormRenderTest.php
> +    $actual = $crawler->filter('form.contact-message-oe-contact-form-corporate-default-form');
this line should get the form, and we work with that after, so in fact this should be the first assert
```suggestion
    $form = $crawler->filter('form.contact-form');
```

2022-02-18 16:19 UTC, drishu commented on modules/oe_whitelabel_contact_forms/tests/src/Kernel/ContactFormRenderTest.php
> +    $actual = $crawler->filter('hr.mt-5.mb-5');
after we get the form as mentioned below we assert only the elements we alter, but in the context of the form
```suggestion
    $wrapper = $form->filter('fieldset');
    $hr = $wrapper->filter('hr.mt-5.mb-5');
    next assert the 2 fields are present..
```

2022-02-18 16:19 UTC, drishu commented on modules/oe_whitelabel_contact_forms/tests/src/Kernel/ContactFormRenderTest.php
> +    $actual = $crawler->filter('div.oe-contact-form__name .field__label');
rather assert that we have a description list, but just the general structure
```
<div>
  <dt>field label</dt>
</div>
<dd>field value</dd>
```

2022-02-18 17:45 UTC, Maxfire commented on modules/oe_whitelabel_contact_forms/tests/src/Kernel/ContactFormRenderTest.php
> +    $actual = $crawler->filter('hr.mt-5.mb-5');
I appended it into the fieldset prefix so it will fail in this way:
![image](https://user-images.githubusercontent.com/6443180/154735016-08331083-1629-4c0e-a526-f56c07a813ec.png)

2022-02-21 07:12 UTC, drishu requested changes

2022-02-21 07:12 UTC, drishu commented on modules/oe_whitelabel_contact_forms/oe_whitelabel_contact_forms.module
> +    // Build the label body pairs for the field_list pattern.
```suggestion
    // Build the label body pairs for the description_list pattern.
```

2022-02-21 07:12 UTC, drishu commented on modules/oe_whitelabel_contact_forms/tests/src/Kernel/ContactFormRenderTest.php
> +
remove this newline

2022-02-21 07:12 UTC, drishu commented on modules/oe_whitelabel_contact_forms/tests/src/Kernel/ContactFormRenderTest.php
> +    $this->assertStringContainsString("<dt>The sender's name</dt>", $html);
```suggestion
    $dt = $html->filter('dt');
    $this->assertEquals("The sender's name", $dt->eq(0)->text());
```
Like here https://github.com/openeuropa/oe_bootstrap_theme/blob/8b535fa36e5663a394df610f7e5d87962a2f29fe/tests/src/Kernel/DropbuttonTest.php#L63

2022-02-21 07:57 UTC, drishu approved these changes

2022-02-21 08:16 UTC, abel-santos-corral approved these changes

2022-02-21 08:18 UTC, merged