OEL-1026:  [oe_whitelabel] Style the event content type
openeuropa/oe_whitelabel pull request #76
Opened 2022-02-21 10:59 UTC by GilNovacomm

Create oe_whitelabel_event

2022-02-21 15:17 UTC, drishu requested changes

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/config/install/core.date_format.oe_whitelabel_news_date.yml
> +id: oe_whitelabel_news_date
you are redefining the new date formatter, event date should be used

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/config/install/core.entity_view_display.node.oe_event.teaser.yml
> +      format_type: oe_whitelabel_news_date
event

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/config/install/core.entity_view_display.node.oe_event.full.yml
> +      format_type: oe_whitelabel_news_date
event

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.info.yml
> +description: Adds additional functionality to the News module
```suggestion
description: Adds additional functionality to the Event module
```

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.info.yml
> +    - core.date_format.oe_whitelabel_news_date
event

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +
remove newline

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +
remove newline

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +  _oe_whitelabel_event_oe_featured_media($variables);
if we name these better we can drop the comments
```suggestion
  _oe_whitelabel_event_preprocess_featured_media($variables);
```

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +  // Preprocess the event Featured media field.
drop

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +  // Preprocess the event Content and Documents field to be used with
drop comment

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +  _oe_whitelabel_event_oe_inpage_navigation($variables);
```suggestion
  _oe_whitelabel_event_preprocess_inpage_nav($variables);
```

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> + */
add function parameter

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +
remove this newline

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +  // If it's not an image and not a video, bail out.
```suggestion
  // If it's not an image bail out.
```
I don't see videos being handled

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +  if ($is_image) {
we already checked above  if it's not an image, what is the point to check now that it is ?

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +  foreach ($variables['content'] as $delta => &$item) {
$delta is not used
```suggestion
  foreach ($variables['content'] as  &$item) {
```

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +  if (!$access->isAllowed()) {
tell me if I'm wrong but isn't the users access checked at route level, and the the access to the field data we can assume granted, or what is the intention ?

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +  $node = \Drupal::service('entity.repository')->getTranslationFromContext($node, $node->language()->getId());
this is not needed, the node loaded is the translation

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/templates/field--node--oe-documents--oe-event.html.twig
> +{%
remove this

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/templates/field--node--oe-event-dates--oe-event.html.twig
> + * Theme override for field oe-publication-date.
not publication

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/templates/field--node--oe-event-dates--oe-event.html.twig
> +{% if label_hidden %}
what is this file for ?

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--full.html.twig
> +  {{ content.body }}
rather {{ content|without(....

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--teaser.html.twig
> +    '#value': content.oe_event_dates|render|striptags,
do with field_value as in the full template

2022-02-21 15:17 UTC, drishu commented on tests/src/Functional/ContentEventRenderTest.php
> +    // Create a News node.
remove this comment, is wrong anyway

2022-02-21 15:17 UTC, drishu commented on tests/src/Functional/ContentEventRenderTest.php
> +
ok but also assert the 2 labels are present in the inpage nav links

2022-02-21 15:17 UTC, drishu commented on modules/oe_whitelabel_event/config/install/core.entity_view_display.node.oe_event.full.yml
> +  body:
we should but these into groups and add templates for the groups not the fields

2022-02-22 09:03 UTC, drishu requested changes

2022-02-22 09:03 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--full.html.twig
> + * News full display.
```suggestion
 * Event full display.
```

2022-02-22 09:03 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> + * @var array $variables
var ?

2022-02-22 09:03 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> + * @var array $variables
var ?

2022-02-22 09:03 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +  $cacheability = CacheableMetadata::createFromRenderArray($variables);
the nodes cache data is already added to $variables, you are not adding anything new, remove everything cache related

2022-02-22 09:03 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.module
> +    if (!array_key_exists('#field_name', $item)
lets split it into 2 checks
```
if (!isset($item['#field_name'])) {
  continue;
}
```
define $fields = ['oe_documents', 'body'] above the loop, no need to redefine this for every item in the loop;
```
if (!in_array($item['#field_name'], $fields)) {
  continue;
}
```

2022-02-22 09:03 UTC, drishu commented on modules/oe_whitelabel_event/oe_whitelabel_event.info.yml
> +name: OpenEuropa Whitelabel Event
lets enable both this and the news in the runner

2022-02-22 09:03 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--full.html.twig
> +  {
what if we don't set date or address, they are optional

2022-02-23 14:04 UTC, drishu requested changes

2022-02-23 14:04 UTC, drishu commented on composer.json
> +        "openeuropa/oe_starter_content": "1.x-dev"
no, need, now you have duplicate

2022-02-23 14:04 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--full.html.twig
> +{% endif %}
we already have one if that checks this logic:
```suggestion
{% if content.oe_event_dates|field_value is not empty %}
  {% set _event_dates %}
    {{ content.oe_event_dates|field_value|safe_join(', ') }}
  {% endset %}
  {% set description_items = description_items|merge([
    {
      term:[{
        'label': content.oe_event_dates|field_label,
        'icon': 'calendar-event',
      }],
      definition: _event_dates,
    }
  ]) %}
{% endif %}
```
same for the one below

2022-02-23 14:04 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--full.html.twig
> +    orientation: 'default',
horizontal

2022-02-23 14:04 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--full.html.twig
> +  <main{{attributes}}>
The content_banner should be a block printed in page.html.twig, where we already have the main and the `<div class="container mt`.

For now we don't do it, but, you dont need this, you just need to top spacing
```suggestion
<div class="mt-md-4-75 mt-4">
```

pls create a follow up to move the content banner into a block

2022-02-23 14:04 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--full.html.twig
> +{% set attributes = attributes.addClass(["mt-md-4-75", "mt-4"]) %}
remove these
```suggestion
```

2022-02-23 14:04 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--full.html.twig
> +    attributes: attributes.addClass(["mt-3", "mb-4"]),
pls dont mix double and single quotes for no reason
```suggestion
    attributes: attributes.addClass(['mt-3, 'mb-4']),
```

2022-02-23 14:04 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--full.html.twig
> +{# Print event #}
remove, such clarifications are not needed

2022-02-23 14:10 UTC, drishu commented on modules/oe_whitelabel_event/templates/node--oe-event--full.html.twig
> +    image: image,
since the content banner should actually be outside of this we have an extra padding that messes up the alignment, we can trick this by removing the padding in one of the elements
```suggestion
    image: image,
    attributes: create_attribute().addClass(['ps-0']),
```

2022-02-23 15:44 UTC, drishu approved these changes

2022-02-23 15:50 UTC, Maxfire approved these changes

2022-02-23 15:51 UTC, escuriola approved these changes

2022-02-23 15:53 UTC, merged