Oel 454
openeuropa/oe_whitelabel pull request #8
Opened 2021-09-14 06:50 UTC by timpevi

2021-09-15 09:02 UTC, drishu requested changes

2021-09-15 09:02 UTC, drishu commented on templates/patterns/search_block/search_block.ui_patterns.yml
> +    additional_classes:
also add additional classes for the input, the button

2021-09-15 09:02 UTC, drishu commented on templates/patterns/search_block/search_block.ui_patterns.yml
> +      preview: "search text"
add a field "additional_elements" of type array, in case more elements need to be injected

2021-09-15 09:02 UTC, drishu commented on templates/patterns/search_block/search_block.ui_patterns.yml
> +  fields:
can we send also attributes for the form pls

2021-09-15 09:02 UTC, drishu commented on templates/patterns/search_block/pattern-search-block.html.twig
> +<form{{ attributes.addClass('search-form', 'search-block-form', additional_classes) }} action="{{ url }}">
create a attributes array
```
{% if attributes is empty %}
  {% set attributes = create_attribute() %}
{% endif %}
```
start adding the classes, action to it, this way if the pattern sends more then the scenario is covered

2021-09-15 09:02 UTC, drishu commented on templates/patterns/search_block/pattern-search-block.html.twig
> + * Default theme implementation for a 'form' element.
```suggestion
 * Default theme implementation for a 'search form' composition.
```

2021-09-15 09:02 UTC, drishu commented on templates/patterns/search_block/pattern-search-block.html.twig
> +  'icon_position': 'after'
make the icon position configurable

2021-09-15 09:02 UTC, drishu commented on templates/patterns/search_block/search_block.ui_patterns.yml
> +  fields:
add icon_position

2021-09-15 09:45 UTC, timpevi commented on templates/patterns/search_block/search_block.ui_patterns.yml
> +    additional_classes:
additional classes for the button not available

2021-09-16 15:39 UTC, drishu approved these changes

2021-09-16 15:40 UTC, Maxfire approved these changes
:+1:

2021-09-16 15:40 UTC, merged