OEL-1147 - Footer
openeuropa/oe_whitelabel pull request #81
Opened 2022-02-23 08:53 UTC by escuriola

2022-02-23 12:25 UTC, drishu requested changes

2022-02-23 12:25 UTC, drishu commented on composer.json
> +        "drupal/twig_tweak": "^3.1"
are we still using twig_tweak ?

2022-02-23 16:23 UTC, drishu requested changes

2022-02-23 16:23 UTC, drishu commented on modules/oe_whitelabel_helper/oe_whitelabel_helper.info.yml
> +  - drupal:twig_tweak
remove this

2022-02-23 16:23 UTC, drishu commented on tests/src/Kernel/FooterBlockTest.php
> +    'twig_tweak',
remove

2022-02-23 16:23 UTC, drishu commented on templates/overrides/navigation/oe-corporate-blocks-eu-footer.html.twig
> +              srcset="{{ bcl_logo_path ~ 'eu/mobile/logo-eu--' ~ current_language_id|to_internal_language_id ~ '.svg' }}">
some rebasing is required, this filter `to_internal_language_id` is missing in this branches code

2022-03-07 18:16 UTC, drishu approved these changes, later dismissed

2022-03-11 21:43 UTC, brummbar requested changes

2022-03-11 21:43 UTC, brummbar commented on templates/overrides/navigation/oe-corporate-blocks-neutral-footer.html.twig
> +  {% include '@oe-bcl/bcl-footer/bcl-footer.html.twig' with {
```suggestion
  {% include '@oe-bcl/footer' with {
```

2022-03-11 21:43 UTC, brummbar commented on templates/overrides/navigation/oe-corporate-blocks-neutral-footer.html.twig
> +  {% include '@oe-bcl/bcl-footer/bcl-footer.html.twig' with {
Same in the other 3 templates.

2022-03-14 14:08 UTC, drishu requested changes
there is a duplicate `div.col-12.col-lg-4`
<img width="516" alt="Screenshot 2022-03-14 at 16 08 21" src="https://user-images.githubusercontent.com/11507647/158189315-5a4d1ef9-496c-436b-98ef-ba6153d57ead.png">

2022-03-14 14:35 UTC, drishu approved these changes

2022-03-14 14:46 UTC, abel-santos-corral approved these changes

2022-03-14 14:47 UTC, Maxfire approved these changes

2022-03-14 14:50 UTC, brummbar approved these changes

2022-03-14 14:57 UTC, merged