OEL-1191: Fix meta publication date and remove OEL-1026 patch.
openeuropa/oe_whitelabel pull request #83
Opened 2022-02-24 08:58 UTC by GilNovacomm

2022-02-28 15:52 UTC, drishu requested changes

2022-02-28 15:52 UTC, drishu commented on modules/oe_whitelabel_news/templates/node--oe-news--full.html.twig
> +    meta: _meta,
there is the same problem here as we had for events
<img width="264" alt="Screenshot 2022-02-28 at 17 31 28" src="https://user-images.githubusercontent.com/11507647/156013258-78588d33-f608-4cb5-8a3e-24270cb0d7db.png">
so lets add the fix, also mention somewhere here in a comment that this is to be removed once OEL-1227 is implemented, same for the events one
```suggestion
    meta: _meta,
    
    attributes: create_attribute().addClass(['ps-0']),
```
I also see the content is not in align with the title, not sure what these changes fix..

2022-02-28 15:52 UTC, drishu commented on modules/oe_whitelabel_news/templates/node--oe-news--full.html.twig
>    <div class="container mt-md-4-75 mt-4">
as with the events, this wrapper is actually already present, so we don't need the container, just the margins (see screenshot)
```suggestion
  <div class="mt-md-4-75 mt-4">
```

2022-02-28 16:57 UTC, drishu requested changes

2022-02-28 16:57 UTC, drishu commented on modules/oe_whitelabel_news/templates/node--oe-news--full.html.twig
> +{% if content.oe_publication_date|render is not empty %}
```suggestion
{% if content.oe_publication_date.isEmpty() %}
```

2022-03-02 07:49 UTC, drishu submitted a review, later dismissed

2022-03-04 08:55 UTC, Maxfire approved these changes

2022-03-04 09:24 UTC, drishu approved these changes

2022-03-04 09:24 UTC, merged