OEL-1213: Address formatted created, tests provided.
openeuropa/oe_whitelabel pull request #84
Opened 2022-02-24 14:54 UTC by Maxfire

Address new formatter created to inline the field, tests also done.

2022-02-28 09:16 UTC, drishu requested changes

2022-02-28 09:16 UTC, drishu commented on modules/oe_whitelabel_helper/src/Plugin/Field/FieldFormatter/AddressInlineFormatter.php
> + *
add a @see so we know where we copied from

2022-02-28 09:16 UTC, drishu commented on modules/oe_whitelabel_helper/tests/src/Kernel/Plugin/Field/FieldFormatter/AddressInlineFormatterTest.php
> + * @group batch2
the batch2 refers to this https://github.com/openeuropa/oe_theme/blob/01b6a8c25ca808bc6b8b7fe968c2452a8706732c/.drone.yml#L154 which we don't have and don't need, please remove

2022-03-04 13:26 UTC, drishu approved these changes

2022-03-07 07:58 UTC, GilNovacomm approved these changes

2022-03-07 07:59 UTC, merged