OEL-1291: News and Event content types renamed.
openeuropa/oe_whitelabel pull request #92
Opened 2022-03-10 12:26 UTC by Maxfire

Content types renamed to make it work with oe_content, tests adapted.

2022-03-10 12:49 UTC, Maxfire commented on composer.json
> +        "openeuropa/oe_starter_content": "dev-OEL-1290",
Temporal until [this](https://github.com/openeuropa/oe_starter_content/pull/5) is merged.

2022-03-11 11:24 UTC, drishu approved these changes, later dismissed
OK for me, but adapt the PR once OEL-1290 is merged

2022-03-11 13:16 UTC, escuriola approved these changes, later dismissed

2022-03-14 12:19 UTC, escuriola approved these changes, later dismissed

2022-03-14 13:29 UTC, drishu approved these changes, later dismissed

2022-03-14 16:48 UTC, brummbar requested changes
We need to rename also the modules themselves.
Let's call oe_whitelabel_starter_news, oe_whitelabel_starter_event.
We need to rename the date format inside the news module.
I've found a problem with the changes in the featured media field, I'll reopen 1290.

2022-03-16 14:07 UTC, escuriola approved these changes, later dismissed

2022-03-16 16:08 UTC, brummbar submitted a review, later dismissed

2022-03-17 12:35 UTC, drishu approved these changes

2022-03-17 12:36 UTC, GilNovacomm approved these changes

2022-03-17 12:37 UTC, merged