OEL-1322: Upgrade oe_whitelabel to PHP 8.0.
openeuropa/oe_whitelabel pull request #98
Opened 2022-03-18 14:15 UTC by escuriola

2022-03-18 15:26 UTC, brummbar requested changes

2022-03-18 15:26 UTC, brummbar commented on .drone.yml
> +      - COMPOSERVER=--2
Same remark as the other PR.

2022-03-21 15:39 UTC, brummbar approved these changes, later dismissed

2022-03-22 10:48 UTC, donquixote approved these changes

2022-03-22 10:55 UTC, brummbar approved these changes

2022-03-22 11:10 UTC, merged