OEL-1283: Add update instructions for paragraphs move
openeuropa/oe_whitelabel pull request #99
Opened 2022-03-21 19:46 UTC by donquixote

[OEL-1283](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1283)

2022-03-31 08:05 UTC, drishu requested changes

2022-03-31 08:05 UTC, drishu commented on README.md
> +#### Paragraphs migration
I don't get this bit, makes more sense to me saying "Upgrading from version x to y" or "Upgrading to version y"

2022-03-31 08:05 UTC, drishu commented on README.md
> +Paragraphs-related theming and functionality has been moved from `oe_bootstrap_theme` to `oe_whitelabel`.
link oe_whitelabel

2022-03-31 12:58 UTC, brummbar requested changes
Not ok for me. We should add only the steps to be taken if we are updating from an old version AND we have oe_bt_paragraphs enabled. Then we need the enabling of the new module through update hook, and that's all.

2022-03-31 12:58 UTC, brummbar commented on README.md
> +Target release: You can upgrade directly to the version that contains this README.md.
Again, what does this mean?

2022-03-31 12:58 UTC, brummbar commented on README.md
> +- For deployment, `drush config:import` will do the job. No update hook needed.
Information NOT needed. We need to write HOW to do the upgrade from previous version. This is general information written in dozens of pages, no need to write it here again.

2022-04-01 13:33 UTC, drishu approved these changes

2022-04-01 15:55 UTC, brummbar requested changes

2022-04-01 15:55 UTC, brummbar commented on README.md
> +If you have the `oe_paragraphs` module enabled, you should create a `hook_update_N()` or `hook_post_update_NAME()` in a custom module, to enable the `oe_whitelabel_paragraphs` module during deploymen
```suggestion
If you have the `oe_paragraphs` module enabled, you should create a `hook_post_update_NAME()` in your code, to enable the `oe_whitelabel_paragraphs` module during deployment.
```

2022-04-01 19:25 UTC, brummbar approved these changes

2022-04-01 19:25 UTC, merged